# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 182ee3d9febbcb9a24a61846df1ba1b308d3ba87430332d6a7bd9ac956c3a7961eb09f597895363019a06ae83f9c79e0529fb900e50dbc35966e23d515f01fe3

test:
  secret_key_base: 1fb6cbf865356275bb9261ef59ef4d4cb84ed81b8a7f18d3912866e58a7cce8facef56af8ad8ccdb5e56510ac21e3375ac695001f514ca54486a9460e33c631b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
